spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:/tmp/main.db
    username: rest_api
    initialization-mode: always
    schema: classpath:schema.sql
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true